version: 2.1

jobs:
  install:
    docker:
      - image: cimg/php:8.5
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-8.5-{{ checksum "composer.json" }}
            - v1-dependencies-8.5-
      - run:
          name: "Installing Composer dependencies"
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: v1-dependencies-8.5-{{ checksum "composer.json" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./

  test:
    docker:
      - image: cimg/php:8.5
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: "Run Tests"
          command: vendor/bin/phpunit

  lint:
    docker:
      - image: cimg/php:8.5
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: "Check code style (Pint)"
          command: vendor/bin/pint --test

workflows:
  version: 2
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
